site_name: YAGA
site_author: Patrick Ofner
markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: './'
repo_url: https://github.com/neurofreiburg/yaga
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - matlab
  hljs_style: stackoverflow-light
  navigation_depth: 5
copyright: Copyright &copy; 2023 Patrick Ofner, Bernstein Center Freiburg @ University of Freiburg
plugins:
  - search
nav:
  - 'index.md'
  - User Guide:
    - 'installation.md'
    - 'usage.md'
    - 'paradigm_scripting.md'
    - 'integration_with_lsl.md'
  - About:
    - 'License': 'license.md'
    - 'release_notes.md'
  - Releases:
    - Latest: https://github.com/neurofreiburg/yaga/releases/latest
