site_name: YAGA
site_author: Patrick Ofner
markdown_extensions:
  - toc:
      permalink: true
repo_url: https://github.com/neurofreiburg/yaga
theme:
  name: readthedocs
  highlightjs: true
  copyright: Copyright &copy; 2023 Patrick Ofner, Neurobiology and Neurotechnology @ University of Freiburg
plugins:
  - search
nav:
  - 'index.md'
  - User Guide:
    - 'installation.md'
    - 'usage.md'
    - 'paradigm_scripting.md'
    - 'integration_with_lsl.md'
  - About:
    - 'License': 'license.md'
    - 'Release Notes': 'release_notes.md'
 