from yaga_modules.paradigm_base import ParadigmBase, ScriptItem
from yaga_modules.pacman import Pacman
import yaga_modules.graphic_objects as GO

class Paradigm(ParadigmBase):
    task_name = 'pacman_demo'

    def __init__(self, paradigm_variables):
        super().__init__(paradigm_variables)

        background = self.registerObject(GO.Image('background_1_mirrored.jpg', depth=10, scale_x=1.78*1.08, scale_y=1.08))
        pacman = self.registerObject(Pacman(item_speed=0.5, item_generator='random', item_generation_frequency=10, frequency=[0.05, 0.15], noise_stddev=3))

        # NOTE: the control LSL stream is generated by the "mousecontroller.py" script in the tools folder; "mousecontroller.py" must be started before YAGA
        pacman.controlStateWithLSLStreams(['MouseControllerStream'], channels=[1])

        # background.activate()
        pacman.activate()

        # sequence definition
        self.script = [ScriptItem(name="trial_start", time=0, time_type='abs', actions=[pacman.start]),
                       ScriptItem(name="trial_end", time=300, time_type='rel', rel_name='trial_start', actions=[])]
